apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-jenkins-demo
  labels:
    app: eks-jenkins-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-jenkins-demo
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: eks-jenkin-demo
          image: mzprateep/eks-jenkin-demo
          ports:
            - containerPort: 8080