  26 lines (21 sloc)  395 Bytes

  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: eks-jenkin-demo
    labels:
      app: eks-jenkin-demo
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: eks-jenkin-demo
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: eks-jenkin-demo
            image: mzprateep/eks-jenkin-demo
            ports:
              - containerPort: 8080